export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_CHARACTER = 'GET_CHARACTER';
export const CHARACTER_LOADING = 'CHARACTER_LOADING';
export const GET_COMICS = 'GET_COMICS';
export const GET_COMIC = 'GET_COMIC';
export const COMIC_LOADING = 'COMIC_LOADING';
